name: GGJest

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.15.x

      - name: Install dependencies
        run: yarn install

      - name: Testing
        run: yarn test
        env:
          CI: true
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
